name: Android Debug Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Repo'yu clone et
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK kur
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Ruby ve Fastlane kurulumu
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Fastlane
        run: gem install fastlane

      # 4. Gradle wrapper'a izin ver
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: android

      # 5. Debug APK oluştur
      - name: Build Debug APK
        run: fastlane build_debug
        working-directory: android

      # 6. Debug APK dosyasını Artifact olarak yükle
      - name: Upload Debug APK
        uses: actions/upload-artifact@v3
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk